// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig, env } from "prisma/config";

// Helper to add SSL and connection pooling parameters to the database URL
const getDatabaseUrl = () => {
  const baseUrl = env("DATABASE_URL");
  if (!baseUrl) return baseUrl;

  // Parse URL to add parameters
  const url = new URL(baseUrl);

  // Add SSL if not present
  if (!url.searchParams.has('sslmode')) {
    url.searchParams.set('sslmode', 'require');
  }

  // Add connection pooling parameters to prevent "too many connections" errors
  if (!url.searchParams.has('connection_limit')) {
    url.searchParams.set('connection_limit', '5');
  }

  if (!url.searchParams.has('pool_timeout')) {
    url.searchParams.set('pool_timeout', '10');
  }

  return url.toString();
};

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: `tsx src/lib/prisma.ts`,
  },
  datasource: {
    url: getDatabaseUrl(),
  },
});
